"use client";

import { useEffect, useMemo, useState } from "react";

type Profile = {
  gender: "男" | "女";
  age: number;
  city: "一线" | "其他";
  marital: "未婚" | "离异" | "丧偶";
  children: "无子女" | "有子女，不随本人生活" | "有子女，共同生活";
  height: number;
  appearance: number;
  education: number;
  income: number;
  savings: number;
  career: number;
  family: number;
};

type SoftKey = "appearance" | "career" | "family";
type ScoreKey = Exclude<keyof Profile,"gender"|"city">;
type WeightItem = { key: ScoreKey; label: string; weight: number; femaleWeight: number; enabled: boolean };
type TargetKind = "balanced" | "compatible" | "aspirational";
type DimensionResult = WeightItem & { score:number; level:string };
type ScoreResult = { score:number; percentile:number; dimensions:DimensionResult[]; groups:Array<(typeof modelGroups)[number] & {weight:number;score:number}> };

const profileSeed: Profile = { gender:"男", age:29, city:"其他", marital:"未婚", children:"无子女", height:178, appearance:7, education:4, income:28, savings:45, career:7, family:7 };
const targetSeeds: Record<TargetKind, Profile> = {
  compatible: { gender:"女", age:28, city:"其他", marital:"未婚", children:"无子女", height:162, appearance:6, education:2, income:12, savings:18, career:6, family:7 },
  balanced: { gender:"女", age:27, city:"其他", marital:"未婚", children:"无子女", height:165, appearance:7, education:3, income:20, savings:30, career:7, family:7 },
  aspirational: { gender:"女", age:26, city:"一线", marital:"未婚", children:"无子女", height:168, appearance:9, education:4, income:35, savings:60, career:9, family:8 },
};

const weightsSeed: WeightItem[] = [
  {key:"appearance",label:"外在与仪表",weight:22,femaleWeight:27,enabled:true},{key:"height",label:"身高",weight:12,femaleWeight:15,enabled:true},
  {key:"income",label:"当前收入",weight:16,femaleWeight:10,enabled:true},{key:"savings",label:"存款与资产",weight:11,femaleWeight:7,enabled:true},{key:"family",label:"家庭资产支持",weight:7,femaleWeight:5,enabled:true},
  {key:"age",label:"年龄竞争力",weight:14,femaleWeight:18,enabled:true},{key:"marital",label:"婚姻状态",weight:6,femaleWeight:6,enabled:true},{key:"children",label:"子女状态",weight:6,femaleWeight:6,enabled:true},
  {key:"career",label:"职业发展",weight:4,femaleWeight:4,enabled:true},{key:"education",label:"教育背景",weight:2,femaleWeight:2,enabled:true},
];

const modelGroups = [
  {key:"looks",label:"外观条件",keys:["appearance","height","age"] as ScoreKey[],color:"#4298a0"},
  {key:"finance",label:"财产条件",keys:["income","savings","family"] as ScoreKey[],color:"#826aa8"},
  {key:"stage",label:"婚恋经历",keys:["marital","children"] as ScoreKey[],color:"#d66f69"},
  {key:"other",label:"发展背景",keys:["career","education"] as ScoreKey[],color:"#d6a640"},
];

const educationLabels = ["高中及以下","大专","普通本科","重点本科","硕士","博士"];
const softMeta: Record<SoftKey, { label:string; short:string; descriptions:string[] }> = {
  appearance: { label:"外在与仪表", short:"大众审美与实际第一印象", descriptions:[
    "未评分。","1分｜明显低于普遍审美，五官、体态与仪表多方面都较弱，通常会被直观评价为“丑”。","2分｜低于普遍审美，即使保持整洁，第一印象仍容易被认为不好看。","3分｜整体偏弱，但通过发型、体态和穿搭改善后可以明显提升。","4分｜略低于普通人水平，干净得体时不至于突兀，但外貌通常不是优势。","5分｜典型普通人，外貌不加分也不明显减分，辨识度较低。","6分｜普通人中较顺眼的一档，整体协调、耐看，偶尔会得到好看评价。","7分｜公认的帅或美，在同事、同学等熟人圈中通常属于外貌优势者。","8分｜很帅或很美，五官、体态与仪表都突出，在多数场合容易被注意。","9分｜顶帅或顶美，接近明星、模特级别，在现实人群中非常少见。","10分｜理论极值：外貌、体态、气质和镜头表现几乎无短板，现实中基本不存在。"] },
  career: { label:"职业发展", short:"结合城市、稳定性、收入与成长性", descriptions:[
    "未评分。","1分｜无稳定工作或长期失业，收入中断且没有清晰职业计划。","2分｜临时工、频繁换岗或高度不稳定的小微企业岗位，收入明显低于当地水平。","3分｜普通小型民企或基础服务岗位，能够就业，但稳定性、收入和成长空间都有限。","4分｜稳定的中小企业、技术或行政岗位，收入接近当地普通水平，有一定可积累能力。","5分｜成熟民企正式员工、专业技术岗位，或非一线城市一般国企/事业单位岗位，稳定与收入较均衡。","6分｜优质国企正式岗、地方银行稳定岗、非一线城市公务员/事业编，或中型科技企业骨干，抗风险能力较好。","7分｜非一线城市优质公务员/事业编、银行核心正式岗、大型国企骨干，或IT大厂成熟专业岗。","8分｜一线城市优质公务员/事业单位核心岗、央国企或银行总部骨干；IT大厂高级岗可达此级，但需扣除裁员风险。","9分｜一线城市核心体制内/央国企重要岗位，兼具稀缺平台、明确晋升与优厚保障；头部银行核心高薪岗也可接近。","10分｜一线城市极稀缺的核心体制内或中央级平台：稳定、待遇、资源、发展和社会认可几乎同时拉满，现实中极少。"] },
  family: { label:"家庭资产支持", short:"住房、资金与长期经济兜底", descriptions:[
    "未评分。","1分｜家庭有严重债务或长期资金缺口，本人需要持续承担主要经济责任。","2分｜家庭负担较重，除无法提供支持外，还需要本人长期补贴。","3分｜基本无法提供经济支持，并有较明显的养老或家庭支出压力。","4分｜主要依靠个人积累，家庭几乎不能提供住房或大额资金支持。","5分｜普通家庭水平，能提供有限的婚礼、应急或小额资金帮助。","6分｜可支持婚礼、购车、租房，或承担一部分首付等阶段性支出。","7分｜可提供较可观的首付、住房支持或稳定的应急经济兜底。","8分｜可直接提供住房或大额资金支持，家庭自身经济负担较低。","9分｜拥有多套房产、企业或充足可调配资产，能形成长期明显助力。","10分｜极少数家庭资产与资源水平，住房、资金和长期保障几乎无短板。"] },
};

const targetInfo: Record<TargetKind,{name:string;tag:string;copy:string;color:string}> = {
  compatible:{name:"兼容",tag:"比你低一档",copy:"目标总分低于你，更容易进入彼此的现实选择范围。",color:"mint"},
  balanced:{name:"匹配",tag:"与你同分",copy:"目标总分与你相当，用条件取舍组成不同的同档画像。",color:"purple"},
  aspirational:{name:"挑战",tag:"比你高一档",copy:"目标总分高于你，候选更稀缺，双向匹配难度更高。",color:"yellow"},
};

function clamp(v:number,min=0,max=100){return Math.min(max,Math.max(min,v))}
function interpolate(value:number,points:Array<[number,number]>){if(value<=points[0][0])return points[0][1];for(let i=1;i<points.length;i++){const[a,b]=points[i-1],[c,d]=points[i];if(value<=c)return b+(d-b)*(value-a)/(c-a)}return points.at(-1)?.[1]??50}
function rarityLevel(score:number){if(score<20)return"明显受限";if(score<40)return"选择面偏窄";if(score<60)return"普通区间";if(score<75)return"有一定优势";if(score<90)return"较有优势";if(score<97)return"突出优势";return"极少数优势"}
function resourceThreshold(key:"income"|"savings",p:Profile){if(key==="income")return p.gender==="女"?(p.city==="一线"?45:35):(p.city==="一线"?60:50);return p.gender==="女"?(p.city==="一线"?90:75):(p.city==="一线"?120:100)}
function metricScore(key:ScoreKey,p:Profile){switch(key){
  case"age":return p.gender==="女"
    ?interpolate(p.age,[[18,52],[22,72],[25,87],[28,92],[30,88],[32,78],[35,60],[38,40],[40,28],[45,10],[50,4],[60,1]])
    :interpolate(p.age,[[18,30],[22,48],[25,64],[28,77],[30,84],[32,88],[35,86],[38,78],[40,70],[45,52],[50,35],[55,20],[60,10],[65,5]])
  case"marital":return p.marital==="未婚"?82:p.marital==="离异"?(p.gender==="男"?52:48):(p.gender==="男"?50:46)
  case"children":return p.children==="无子女"?82:p.children==="有子女，不随本人生活"?(p.gender==="男"?52:48):(p.gender==="男"?32:28)
  case"height":{const mean=p.gender==="男"?169.7:158,sd=p.gender==="男"?6.5:6,z=(p.height-mean)/sd;return clamp(100/(1+Math.exp(-1.702*z)),2,99)}
  case"appearance":return interpolate(p.appearance,p.gender==="女"?[[1,1],[2,3],[3,9],[4,23],[5,48],[6,70],[7,90],[8,95.5],[9,98],[10,99]]:[[1,1],[2,3],[3,10],[4,25],[5,50],[6,72],[7,90],[8,96.2],[9,98.3],[10,99]])
  case"education":return (p.gender==="女"?[32,50,68,80,90,96]:[22,38,58,72,86,95])[p.education]??50
  case"income":return interpolate(p.income/resourceThreshold("income",p),[[0,2],[.1,18],[.2,50],[.3,62],[.5,76],[.7,86],[1,94],[1.5,97],[2.5,98.5],[4,99.2]])
  case"savings":return interpolate(p.savings/resourceThreshold("savings",p),[[0,2],[.05,15],[.15,50],[.3,70],[.5,82],[.75,90],[1,95],[1.5,97.5],[2.5,99],[4,99.5]])
  case"career":return interpolate(p.career+(p.gender==="女"?.7:0),[[1,2],[2,6],[3,13],[4,25],[5,42],[6,60],[7,75],[8,87],[9,95],[10,99]])
  case"family":return interpolate(p.family+(p.gender==="女"?.6:0),[[1,2],[2,6],[3,14],[4,28],[5,45],[6,61],[7,76],[8,88],[9,96],[10,99.5]])
  default:return 50
}}
function normalCdf(z:number){const sign=z<0?-1:1,x=Math.abs(z)/Math.sqrt(2),t=1/(1+.3275911*x),erf=1-(((((1.061405429*t-1.453152027)*t)+1.421413741)*t-.284496736)*t+.254829592)*t*Math.exp(-x*x);return.5*(1+sign*erf)}
function inverseNormalCdf(probability:number){const p=clamp(probability,.0001,.9999),a=[-39.69683028665376,220.9460984245205,-275.9285104469687,138.357751867269,-30.66479806614716,2.506628277459239],b=[-54.47609879822406,161.5858368580409,-155.6989798598866,66.80131188771972,-13.28068155288572],c=[-.007784894002430293,-.3223964580411365,-2.400758277161838,-2.549732539343734,4.374664141464968,2.938163982698783],d=[.007784695709041462,.3224671290700398,2.445134137142996,3.754408661907416],low=.02425,high=1-low;if(p<low){const q=Math.sqrt(-2*Math.log(p));return(((((c[0]*q+c[1])*q+c[2])*q+c[3])*q+c[4])*q+c[5])/((((d[0]*q+d[1])*q+d[2])*q+d[3])*q+1)}if(p>high){const q=Math.sqrt(-2*Math.log(1-p));return-(((((c[0]*q+c[1])*q+c[2])*q+c[3])*q+c[4])*q+c[5])/((((d[0]*q+d[1])*q+d[2])*q+d[3])*q+1)}const q=p-.5,r=q*q;return(((((a[0]*r+a[1])*r+a[2])*r+a[3])*r+a[4])*r+a[5])*q/(((((b[0]*r+b[1])*r+b[2])*r+b[3])*r+b[4])*r+1)}
function percentileZ(score:number){return inverseNormalCdf(clamp(score,.01,99.99)/100)}
function zPercent(z:number){return clamp(normalCdf(z)*100,1,99)}
function validWeight(value:unknown,fallback:number){return typeof value==="number"&&Number.isFinite(value)&&value>0?value:fallback}
function normalAggregate(items:Array<{score:number;weight:number}>){if(!items.length)return 0;const total=items.reduce((s,x)=>s+x.weight,0)||1,zs=items.map(x=>({...x,z:percentileZ(x.score)})),average=zs.reduce((s,x)=>s+x.z*x.weight,0)/total,strongest=Math.max(...zs.map(x=>x.z)),weakest=Math.min(...zs.map(x=>x.z));const positive=Math.max(0,strongest-average)*.2+Math.max(0,strongest-1.2816)*.12,negative=Math.min(0,weakest-average)*.24+Math.min(0,weakest+1.2816)*.18;return zPercent(average+positive+negative)}
function wealthAggregate(items:Array<{score:number;weight:number}>){if(!items.length)return 0;const total=items.reduce((s,x)=>s+x.weight,0)||1,zs=items.map(x=>({...x,z:percentileZ(x.score)})).sort((a,b)=>b.z-a.z),average=zs.reduce((s,x)=>s+x.z*x.weight,0)/total,strongest=zs[0].z,weakest=zs.at(-1)?.z??strongest;const baseline=average*.78+weakest*.22,substitution=clamp((strongest-.6745)/1.652,0,1),dominant=strongest+Math.max(0,zs[1]?.z??0)*.12+Math.max(0,zs[2]?.z??0)*.05;return zPercent(baseline*(1-substitution)+dominant*substitution)}
function appearanceAggregate(items:Array<{score:number;weight:number}>){if(!items.length)return 0;const total=items.reduce((s,x)=>s+x.weight,0)||1,zs=items.map(x=>({...x,z:percentileZ(x.score)})),average=zs.reduce((s,x)=>s+x.z*x.weight,0)/total,weakest=Math.min(...zs.map(x=>x.z)),allRoundBonus=Math.max(0,weakest)*.08,bottleneck=Math.min(0,weakest-average)*.55+Math.min(0,weakest+1.2816)*.22;return zPercent(average+bottleneck+allRoundBonus)}
function calculate(p:Profile,weights:WeightItem[]):ScoreResult{const active=weights.filter(w=>w.enabled).map(w=>{const seed=weightsSeed.find(x=>x.key===w.key)!,male=validWeight(w.weight,seed.weight),female=validWeight(w.femaleWeight,seed.femaleWeight);return{...w,femaleWeight:female,weight:p.gender==="女"?female:male}}),total=active.reduce((s,w)=>s+w.weight,0)||1;const dimensions:DimensionResult[]=active.map(w=>{const score=Math.round(metricScore(w.key,p));return{...w,score,level:rarityLevel(score)}});const groups=modelGroups.map(group=>{const items=dimensions.filter(item=>group.keys.includes(item.key)),weight=items.reduce((s,item)=>s+item.weight,0),aggregate=group.key==="looks"?appearanceAggregate:group.key==="finance"?wealthAggregate:normalAggregate,groupScore=Math.round(aggregate(items));return{...group,weight:weight/total*100,score:groupScore}});const groupInputs=groups.filter(g=>g.weight>0).map(g=>({score:g.score,weight:g.weight}));const base=normalAggregate(groupInputs),looksScore=groups.find(x=>x.key==="looks")?.score??50,financeScore=groups.find(x=>x.key==="finance")?.score??50,criticalZ=[percentileZ(looksScore),percentileZ(financeScore)],bestCritical=Math.max(...criticalZ),worstCritical=Math.min(...criticalZ),positiveExtreme=Math.max(0,bestCritical-.6745)*.5,negativeExtreme=Math.min(0,worstCritical+.6745)*.55,appearanceScore=dimensions.find(x=>x.key==="appearance")?.score??72,appearanceAccent=(percentileZ(appearanceScore)-percentileZ(72))*(p.gender==="女"?.11:.1);const score=Math.round(zPercent(percentileZ(base)+positiveExtreme+negativeExtreme+appearanceAccent));return{score,percentile:score,dimensions,groups}}
function targetScoreCap(kind:TargetKind,ownScore:number){const safeScore=Number.isFinite(ownScore)?ownScore:50;return kind==="compatible"?Math.max(1,safeScore-12):kind==="balanced"?safeScore:Math.min(99,safeScore+8)}
function targetAtLevel(level:number,own:Profile):Profile{const gender=own.gender==="男"?"女":"男",idealAge=gender==="女"?26:32,weakAge=gender==="女"?45:55,lowHeight=gender==="女"?148:158,highHeight=gender==="女"?172:185,t=clamp(level,0,1);return{gender,city:own.city,age:Math.round(weakAge+(idealAge-weakAge)*t),marital:t>=.46?"未婚":"离异",children:t>=.55?"无子女":t>=.28?"有子女，不随本人生活":"有子女，共同生活",height:Math.round(lowHeight+(highHeight-lowHeight)*t),appearance:Math.round(2+7*t),education:Math.round(5*t),income:Math.round(1+119*t*t),savings:Math.round(240*t*t),career:Math.round(2+8*t),family:Math.round(2+8*t)}}
function targetForCap(cap:number,own:Profile,weights:WeightItem[]){let best=targetAtLevel(0,own),bestScore=calculate(best,weights).score;for(let i=1;i<=1000;i++){const candidate=targetAtLevel(i/1000,own),score=calculate(candidate,weights).score;if(score<=cap&&score>=bestScore){best=candidate;bestScore=score}}return best}
function difficulty(own:ScoreResult,target:ScoreResult){const gap=target.score-own.score,ownGroups=Object.fromEntries(own.groups.map(x=>[x.key,x.score])),targetGroups=Object.fromEntries(target.groups.map(x=>[x.key,x.score])),criticalGap=Math.max(0,(targetGroups.looks??50)-(ownGroups.looks??50),(targetGroups.finance??50)-(ownGroups.finance??50)),looksBarrier=interpolate(targetGroups.looks??50,[[0,0],[50,0],[72,8],[85,20],[95,42],[99,60]]),financeBarrier=interpolate(targetGroups.finance??50,[[0,0],[50,0],[72,6],[85,15],[95,28],[99,45],[100,60]]),gapPressure=gap>=0?gap*1.15:gap*.3,pressure=gapPressure+criticalGap*.28+looksBarrier+financeBarrier+Math.max(0,target.score-82)*.2;const levels=[
  {max:2,label:"容易",step:6,copy:"目标条件较常见，也落在你的现实选择范围内。"},
  {max:13,label:"较易",step:5,copy:"目标不算稀缺，双方条件有较大的相遇与互选空间。"},
  {max:25,label:"有挑战",step:4,copy:"目标已出现稀缺项，需要偏好契合或个人优势来提高机会。"},
  {max:39,label:"较难",step:3,copy:"目标的突出条件明显收窄了候选范围，匹配需要更多运气。"},
  {max:55,label:"很难",step:2,copy:"目标集中在少见人群，单靠其他普通条件很难补足差距。"},
  {max:Infinity,label:"基本不可能",step:1,copy:"目标包含极稀缺条件，现实候选很少，双向选择机会也会更低。"},
];return levels.find(x=>pressure<=x.max)??levels.at(-1)!}

function InfoDot({text}:{text:string}){return <span className="info-dot" tabIndex={0} aria-label={text}>i<span>{text}</span></span>}
function itemInfo(key:ScoreKey|null,p:Profile,weights:WeightItem[]){if(!key)return"该项用于确定比较人群，让结果更贴近你的现实环境，本身不直接计分。";const w=weights.find(x=>x.key===key);if(!w?.enabled)return"该项当前已停用，不参与综合稀缺度计算。";const score=Math.round(metricScore(key,p)),level=rarityLevel(score);const basis=key==="age"?` 当前使用${p.gender}性年龄曲线，并与外在、身高共同形成外观条件；年龄跨过关键阶段后会成为明显短板。`:key==="marital"?" 婚史会改变可进入的候选范围，并与子女状态共同形成婚恋经历。":key==="children"?" 子女是否共同生活会带来不同的时间、经济和家庭整合成本。":key==="height"?" 会结合同性别平均身高判断相对位置，并作为外观条件中的共同门槛。":key==="income"||key==="savings"?` 当前${p.gender}性·${p.city}曲线的主要收敛点约为 ${resourceThreshold(key,p)} 万；达到前提升较快，超过后边际收益递减。`:key==="family"?" 只描述家庭可提供的住房、资金和经济兜底，不评价家庭关系；达到很高水平时，可独立形成财产优势。":"";return`当前单项位置 ${score}/100 · ${level}。${basis}这是婚恋选择面的估计，不代表个人价值。`}

function NumberField({label,value,onChange,unit,min=0,max=999,info}:{label:string;value:number;onChange:(v:number)=>void;unit?:string;min?:number;max?:number;info?:string}){
  const[draft,setDraft]=useState(String(value));
  useEffect(()=>setDraft(String(value)),[value]);
  const change=(raw:string)=>{setDraft(raw);if(raw!==""){const parsed=Number(raw);if(Number.isFinite(parsed))onChange(parsed)}};
  const finish=()=>{if(draft===""){setDraft(String(value));return}const parsed=Number(draft);const next=Math.min(max,Math.max(min,Number.isFinite(parsed)?parsed:value));setDraft(String(next));if(next!==value)onChange(next)};
  return <label className="field"><span className="field-label">{label}{info&&<InfoDot text={info}/>}</span><div><input aria-label={label} type="number" inputMode="numeric" step="1" value={draft} min={min} max={max} onFocus={e=>e.currentTarget.select()} onWheel={e=>e.currentTarget.blur()} onChange={e=>change(e.target.value)} onBlur={finish}/>{unit&&<em>{unit}</em>}</div></label>
}

function SoftSlider({kind,value,onChange,city}:{kind:SoftKey;value:number;onChange:(v:number)=>void;city:string}){const meta=softMeta[kind];return <div className="soft-card"><div className="soft-title"><div><b>{meta.label}</b><span>{meta.short}</span></div><strong>{value}<small>/10</small></strong></div><input aria-label={`${meta.label}评分`} type="range" min="1" max="10" step="1" value={value} onChange={e=>onChange(Number(e.target.value))}/><div className="scale"><span>1</span><span>5</span><span>10</span></div><p key={value}><i>当前等级</i>{meta.descriptions[value]}</p>{kind==="appearance"&&<small className="model-caveat">仅描述大众审美中的相对位置，不代表个人价值。</small>}{kind==="career"&&<small className="model-caveat">当前选择：{city}城市口径。IT大厂等高薪岗位会同时考虑波动和裁员风险。</small>}</div>}

function Basics({profile,onChange,weights}:{profile:Profile;onChange:(p:Profile)=>void;weights:WeightItem[]}){const set=<K extends keyof Profile>(k:K,v:Profile[K])=>onChange({...profile,[k]:v});return <div className="basics-grid"><label className="field"><span className="field-label">性别<InfoDot text={itemInfo(null,profile,weights)}/></span><select value={profile.gender} onChange={e=>set("gender",e.target.value as Profile["gender"])}><option>男</option><option>女</option></select></label><NumberField label="年龄" value={profile.age} min={18} max={65} unit="岁" info={itemInfo("age",profile,weights)} onChange={v=>set("age",v)}/><label className="field"><span className="field-label">婚姻状态<InfoDot text={itemInfo("marital",profile,weights)}/></span><select value={profile.marital} onChange={e=>set("marital",e.target.value as Profile["marital"])}><option>未婚</option><option>离异</option><option>丧偶</option></select></label><label className="field"><span className="field-label">子女状态<InfoDot text={itemInfo("children",profile,weights)}/></span><select value={profile.children} onChange={e=>set("children",e.target.value as Profile["children"])}><option>无子女</option><option>有子女，不随本人生活</option><option>有子女，共同生活</option></select></label><label className="field"><span className="field-label">常住城市<InfoDot text="城市不直接加减分，只对收入和储蓄的比较基线做轻微校准。一线指北京、上海、广州、深圳。"/></span><select value={profile.city} onChange={e=>set("city",e.target.value as Profile["city"])}><option value="一线">一线（北上广深）</option><option value="其他">其他城市</option></select></label><NumberField label="身高" value={profile.height} min={140} max={210} unit="cm" info={itemInfo("height",profile,weights)} onChange={v=>set("height",v)}/><label className="field"><span className="field-label">最高学历<InfoDot text={itemInfo("education",profile,weights)}/></span><select value={profile.education} onChange={e=>set("education",Number(e.target.value))}>{educationLabels.map((x,i)=><option value={i} key={x}>{x}</option>)}</select></label><NumberField label="税前年收入" value={profile.income} unit="万" info={itemInfo("income",profile,weights)} onChange={v=>set("income",v)}/><NumberField label="可支配储蓄" value={profile.savings} unit="万" info={itemInfo("savings",profile,weights)} onChange={v=>set("savings",v)}/></div>}

function ResultHero({profile,weights}:{profile:Profile;weights:WeightItem[]}){const result=useMemo(()=>calculate(profile,weights),[profile,weights]);const[showParts,setShowParts]=useState(false);const top=[...result.dimensions].sort((a,b)=>b.score-a.score)[0];return <section className="result-hero"><div className="result-copy"><span className="mini-label">你的条件画像</span><h1>{result.percentile>=90?"少数优势型":result.percentile>=72?"优势清晰型":result.percentile>=50?"稳健平衡型":"选择面聚焦型"}</h1><p>这个分数代表你的条件在现实婚恋选择中的综合位置。<b>{top?.label}</b>是当前最突出的稀缺优势。</p><div className="result-actions"><button onClick={()=>document.querySelector("#profile-editor")?.scrollIntoView({behavior:"smooth"})}>调整我的资料</button><span>比较口径：{profile.gender} · {profile.city} · {profile.marital} · {profile.children}</span></div></div><div className="result-visual"><div className="orbit one"/><div className="orbit two"/><div className="avatar-shape"><i/><b/><span/></div></div><div className={`score-summary ${showParts?"parts-view":""}`}>{showParts?<><div className="score-mode-head"><small>选择面拆解</small><button onClick={()=>setShowParts(false)}>← 返回总分</button></div><div className="group-scores">{result.groups.map(group=><div key={group.key} style={{borderColor:group.color}}><span>{group.label}<small>影响度 {group.weight.toFixed(0)}%</small></span><strong>{group.score}</strong></div>)}</div><div className="score-parts">{result.dimensions.map(item=><div key={item.key}><span>{item.label}<small>{item.level}</small></span><i><b style={{width:`${item.score}%`}}/></i><strong>{item.score}</strong></div>)}</div><p className="formula-note">财产取强项，外观看短板；各组完成组合后再进入正态分布汇总。</p></>:<><div className="score-mode-head"><small>综合条件位置</small><button onClick={()=>setShowParts(true)}>查看分项 →</button></div><strong>{result.score}</strong><span>/100</span><div className="percent-bar"><i style={{width:`${result.percentile}%`}}/></div><p>当前婚恋选择面约处于 <b>{result.percentile}%</b> 水平</p><small className="score-explain">分数越高，兼具相似条件与选择优势的人越少</small></>}</div></section>}

function ProfileEditor({profile,onChange,weights}:{profile:Profile;onChange:(p:Profile)=>void;weights:WeightItem[]}){const set=(k:SoftKey,v:number)=>onChange({...profile,[k]:v});return <section className="editor-section" id="profile-editor"><div className="section-heading"><span>01</span><div><h2>完善你的条件画像</h2><p>拖动评分时，对应等级的具体行为描述会同步变化。</p></div></div><div className="white-panel"><h3>基础条件</h3><Basics profile={profile} onChange={onChange} weights={weights}/></div><div className="soft-grid">{(Object.keys(softMeta) as SoftKey[]).map(k=><SoftSlider key={k} kind={k} value={profile[k]} city={profile.city} onChange={v=>set(k,v)}/>)}</div></section>}

function MatchChoices({own,onOpen}:{own:ScoreResult;onOpen:(kind:TargetKind)=>void}){return <section className="match-page match-overview"><div className="page-intro"><span className="mini-label">基于你的 {own.score} 分生成</span><h1>选择一个目标档位</h1><p>每个档位对应一个固定总分预算。进入后，你可以重新分配各项条件，但不能超过该档位的总分上限。</p></div><div className="target-cards">{(Object.keys(targetInfo) as TargetKind[]).map(k=>{const info=targetInfo[k],cap=targetScoreCap(k,own.score),relation=k==="compatible"?`比你低 ${own.score-cap} 分`:k==="balanced"?"与你同分":`比你高 ${cap-own.score} 分`;return <button key={k} className={info.color} onClick={()=>onOpen(k)}><span>{info.tag}</span><div className="target-icon"><i/><b/></div><h2>{info.name}</h2><p>{info.copy}</p><div className="target-score"><strong>{cap}</strong><small>总分预算</small><em>{relation}</em></div><b className="enter-target">进入配置 →</b></button>})}</div><div className="budget-principle"><b>同一个总分，可以有很多种组合</b><span>例如提高对方的外在或收入要求后，需要降低身高、储蓄、学历等其他要求，才能留在当前档位。</span></div></section>}

function TargetEditor({kind,target,onChange,own,ownProfile,weights,cap,onBack}:{kind:TargetKind;target:Profile;onChange:(p:Profile)=>void;own:ScoreResult;ownProfile:Profile;weights:WeightItem[];cap:number;onBack:()=>void}){const result=calculate(target,weights),level=difficulty(own,result),info=targetInfo[kind],remaining=Math.max(0,cap-result.score),[notice,setNotice]=useState<{text:string;blocked:boolean}>({text:"可以先降低一项，再把省下的分数分配给更在意的条件。",blocked:false}),[revision,setRevision]=useState(0);const tryChange=(next:Profile)=>{const nextScore=calculate(next,weights).score;if(nextScore>cap){setNotice({text:`这次调整会达到 ${nextScore} 分，超过${info.name}档 ${cap} 分上限。请先降低其他条件。`,blocked:true});setRevision(n=>n+1);return}onChange(next);setNotice({text:nextScore===cap?"预算已用满。想继续提高某项，需要先降低另一项。":`还可使用 ${cap-nextScore} 分预算。`,blocked:false})};const set=(k:SoftKey,v:number)=>tryChange({...target,[k]:v});const reset=()=>{onChange(targetForCap(cap,ownProfile,weights));setNotice({text:"已恢复为该档位的均衡推荐画像。",blocked:false});setRevision(n=>n+1)};return <section className="match-page target-detail"><button className="back-target" onClick={onBack}>← 返回三个档位</button><div className="target-detail-head"><div><span className="mini-label">{info.name}档 · {info.tag}</span><h1>{cap} 分条件预算</h1><p>当前画像使用 {result.score} 分，剩余 {remaining} 分。调整不会突破上限，也不会自动替你降低其他条件。</p></div><button onClick={reset}>恢复推荐值</button></div><div className="target-budget"><div className="budget-score"><span>已用预算</span><strong>{result.score}<small> / {cap}</small></strong><div><i style={{width:`${Math.min(100,result.score/cap*100)}%`}}/></div></div><div className="budget-remaining"><span>剩余</span><strong>{remaining}</strong><small>分</small></div><div className="difficulty"><span>匹配难度</span><b>{level.label}</b><div>{[1,2,3,4,5,6].map(n=><i className={n<=level.step?"on":""} key={n}/>)}</div></div><p className={notice.blocked?"blocked":""}>{notice.text}</p></div><div className="budget-groups">{result.groups.map(group=><div key={group.key} style={{borderColor:group.color}}><span>{group.label}</span><strong>{group.score}</strong></div>)}</div><div className="white-panel"><h3>分配基础条件</h3><Basics key={`basics-${revision}`} profile={target} onChange={tryChange} weights={weights}/></div><div className="target-soft">{(Object.keys(softMeta) as SoftKey[]).map(k=><SoftSlider key={`${k}-${revision}`} kind={k} value={target[k]} city={target.city} onChange={v=>set(k,v)}/>)}</div></section>}

function SettingsPage({weights,setWeights,saved,onSave}:{weights:WeightItem[];setWeights:(next:WeightItem[])=>void;saved:boolean;onSave:()=>void}){
  const active=weights.filter(w=>w.enabled),maleTotal=active.reduce((s,w)=>s+w.weight,0)||1,femaleTotal=active.reduce((s,w)=>s+w.femaleWeight,0)||1;
  return <section className="settings-page">
    <div className="page-intro"><span className="mini-label">模型设置 · V1.3</span><h1>优势会提升，但不会无限放大</h1><p>外貌、收入和储蓄都使用收敛曲线：达到关键阈值前提升更快，超过阈值后仍会增加，但边际收益逐步降低。</p></div>
    <div className="age-curve-note"><div><b>外貌7分是收敛点</b><span>男女都在7分前获得更明显提升；7分后继续变好仍会加分，但8、9、10分之间的收益逐级缩小。</span></div><div><b>男女资源阈值不同</b><span>其他城市男性收入/储蓄约50/100万，女性约35/75万；一线城市分别提高到60/120万和45/90万。</span></div><div><b>阈值不是封顶</b><span>达到阈值代表进入优势区，不是满分。超过后仍能体现稀缺性，只是不再按阈值前的速度增长。</span></div></div>
    <div className="group-rule-cards four">{modelGroups.map(group=>{const items=active.filter(w=>group.keys.includes(w.key)),male=items.reduce((s,w)=>s+w.weight,0)/maleTotal*100,female=items.reduce((s,w)=>s+w.femaleWeight,0)/femaleTotal*100;return <div key={group.key} style={{borderTopColor:group.color}}><span>{group.label}</span><strong className="gender-weight"><i>男 {male.toFixed(0)}%</i><i>女 {female.toFixed(0)}%</i></strong><small>模型影响度 · {group.keys.map(key=>weights.find(w=>w.key===key)?.label).filter(Boolean).join(" · ")}</small></div>})}</div>
    <div className="settings-card"><div className="settings-head"><div><h2>男女子项影响度</h2><p>每一项都可以分别调整男性与女性权重</p></div><button onClick={onSave}>{saved?"已保存 ✓":"保存设置"}</button></div>{weights.map((w,i)=><div className={`weight-line gender-line ${!w.enabled?"off":""}`} key={w.key}><span>{w.label}</span><label><small>男 {w.weight}</small><input aria-label={`${w.label}男性影响度`} type="range" min="1" max="30" value={w.weight} onChange={e=>setWeights(weights.map((x,n)=>n===i?{...x,weight:Number(e.target.value)}:x))}/></label><label><small>女 {w.femaleWeight}</small><input aria-label={`${w.label}女性影响度`} type="range" min="1" max="30" value={w.femaleWeight} onChange={e=>setWeights(weights.map((x,n)=>n===i?{...x,femaleWeight:Number(e.target.value)}:x))}/></label><button aria-label={`${w.enabled?"停用":"启用"}${w.label}`} className={w.enabled?"toggle on":"toggle"} onClick={()=>setWeights(weights.map((x,n)=>n===i?{...x,enabled:!x.enabled}:x))}><i/></button></div>)}</div>
    <div className="research-card"><div><span>模型逻辑</span><h2>先按性别比较，再按现实关系组合</h2></div><ul><li><b>分段收敛曲线</b><p>阈值前使用较陡曲线，阈值后切换为缓慢增长，避免少数极高数值无限拉开总分。</p></li><li><b>财产取强项</b><p>收入、储蓄和家庭资产在高位区间可以互相替代；一个资源很强就能形成财产优势。</p></li><li><b>外观短板与外貌微调</b><p>身高和年龄短板仍会影响外观组；外貌达到7分后，独立加成也会随曲线一起逐渐收敛。</p></li></ul><div className="source-links"><a href="https://arxiv.org/abs/1401.5710" target="_blank" rel="noreferrer">中国婚恋网站行为研究</a><a href="https://journals.sagepub.com/doi/10.1177/0192513X231155603" target="_blank" rel="noreferrer">上海线上择偶年龄研究</a><a href="https://www.demographic-research.org/articles/volume/41/3" target="_blank" rel="noreferrer">初婚与再婚匹配研究</a><a href="https://link.springer.com/article/10.1186/s40711-015-0023-9" target="_blank" rel="noreferrer">CFPS再婚影响因素</a></div><p className="assumption-note">男女差异与收敛阈值反映的是当前产品的建模假设，不代表个人价值，也不等同于自然规律。具体曲线仍需真实匿名样本持续校准。</p></div>
  </section>
}

export default function Home(){const[page,setPage]=useState<"profile"|"match"|"settings">("profile");const[profile,setProfile]=useState(profileSeed);const[targets,setTargets]=useState(targetSeeds);const[active,setActive]=useState<TargetKind>("balanced");const[targetOpen,setTargetOpen]=useState(false);const[weights,setWeights]=useState(weightsSeed);const[saved,setSaved]=useState(false);useEffect(()=>{const raw=localStorage.getItem("hepai-config-v2");if(raw)try{const old=JSON.parse(raw) as WeightItem[];setWeights(weightsSeed.map(seed=>{const stored=old.find(item=>item.key===seed.key);return stored?{...seed,weight:validWeight(stored.weight,seed.weight),femaleWeight:validWeight(stored.femaleWeight,seed.femaleWeight),enabled:typeof stored.enabled==="boolean"?stored.enabled:seed.enabled}:seed}))}catch{}},[]);const own=calculate(profile,weights),cap=targetScoreCap(active,own.score);const updateTarget=(p:Profile)=>setTargets(current=>({...current,[active]:p}));const openTarget=(kind:TargetKind)=>{const nextCap=targetScoreCap(kind,own.score);setActive(kind);setTargets(current=>({...current,[kind]:targetForCap(nextCap,profile,weights)}));setTargetOpen(true)};const navigate=(next:typeof page)=>{setPage(next);setTargetOpen(false)};const save=()=>{localStorage.setItem("hepai-config-v2",JSON.stringify(weights));setSaved(true);setTimeout(()=>setSaved(false),1600)};
  return <main><header><button className="logo" onClick={()=>navigate("profile")}><i>合</i><span>合拍<small>婚恋条件匹配工具</small></span></button><nav><button className={page==="profile"?"active":""} onClick={()=>navigate("profile")}>我的画像</button><button className={page==="match"?"active":""} onClick={()=>navigate("match")}>目标推荐</button><button className={page==="settings"?"active":""} onClick={()=>navigate("settings")}>模型设置</button></nav><div className="privacy"><i/>资料仅保存在本机</div></header>
  {page==="profile"&&<><ResultHero profile={profile} weights={weights}/><ProfileEditor profile={profile} onChange={setProfile} weights={weights}/></>}
  {page==="match"&&(targetOpen?<TargetEditor kind={active} target={targets[active]} onChange={updateTarget} own={own} ownProfile={profile} weights={weights} cap={cap} onBack={()=>setTargetOpen(false)}/>:<MatchChoices own={own} onOpen={openTarget}/>)}
  {page==="settings"&&<SettingsPage weights={weights} setWeights={setWeights} saved={saved} onSave={save}/>} {/* settings view */}
  <footer><b>合拍</b><span>结果用于自我认知和偏好梳理，不代表人的价值。</span><a href="https://www.16personalities.com/free-personality-test" target="_blank" rel="noreferrer">界面风格参考</a></footer></main>}
