"use client";

import { useEffect, useMemo, useState } from "react";

type Profile = {
  gender: "男" | "女";
  age: number;
  city: string;
  height: number;
  appearance: number;
  education: number;
  income: number;
  savings: number;
  career: number;
  family: number;
};

type SoftKey = "appearance" | "career" | "family";
type WeightItem = { key: keyof Profile; label: string; weight: number; enabled: boolean };
type TargetKind = "balanced" | "compatible" | "aspirational";

const profileSeed: Profile = { gender:"男", age:29, city:"新一线", height:178, appearance:7, education:4, income:28, savings:45, career:7, family:7 };
const targetSeeds: Record<TargetKind, Profile> = {
  compatible: { gender:"女", age:28, city:"新一线", height:162, appearance:6, education:2, income:12, savings:18, career:6, family:7 },
  balanced: { gender:"女", age:27, city:"新一线", height:165, appearance:7, education:3, income:20, savings:30, career:7, family:7 },
  aspirational: { gender:"女", age:26, city:"一线", height:168, appearance:9, education:4, income:35, savings:60, career:9, family:8 },
};

const weightsSeed: WeightItem[] = [
  {key:"appearance",label:"外在与仪表",weight:23,enabled:true},{key:"height",label:"身高",weight:17,enabled:true},
  {key:"income",label:"当前收入",weight:17,enabled:true},{key:"savings",label:"存款与资产",weight:13,enabled:true},
  {key:"age",label:"年龄适配",weight:9,enabled:true},{key:"family",label:"家庭支持",weight:8,enabled:true},
  {key:"career",label:"职业发展",weight:7,enabled:true},{key:"education",label:"教育背景",weight:6,enabled:true},
];

const modelGroups = [
  {key:"looks",label:"外观条件",keys:["appearance","height"] as (keyof Profile)[],color:"#4298a0"},
  {key:"finance",label:"经济条件",keys:["income","savings","family"] as (keyof Profile)[],color:"#826aa8"},
  {key:"other",label:"其他条件",keys:["age","career","education"] as (keyof Profile)[],color:"#d6a640"},
];

const educationLabels = ["高中及以下","大专","普通本科","重点本科","硕士","博士"];
const newFirstTierCities = ["成都","杭州","重庆","武汉","苏州","西安","南京","长沙","郑州","天津","合肥","青岛","东莞","宁波","佛山"];
const softMeta: Record<SoftKey, { label:string; short:string; descriptions:string[] }> = {
  appearance: { label:"外在与仪表", short:"大众审美与实际第一印象", descriptions:[
    "未评分。","1分｜明显低于普遍审美，五官、体态与仪表多方面都较弱，通常会被直观评价为“丑”。","2分｜低于普遍审美，即使保持整洁，第一印象仍容易被认为不好看。","3分｜整体偏弱，但通过发型、体态和穿搭改善后可以明显提升。","4分｜略低于普通人水平，干净得体时不至于突兀，但外貌通常不是优势。","5分｜典型普通人，外貌不加分也不明显减分，辨识度较低。","6分｜普通人中较顺眼的一档，整体协调、耐看，偶尔会得到好看评价。","7分｜公认的帅或美，在同事、同学等熟人圈中通常属于外貌优势者。","8分｜很帅或很美，五官、体态与仪表都突出，在多数场合容易被注意。","9分｜顶帅或顶美，接近明星、模特级别，在现实人群中非常少见。","10分｜理论极值：外貌、体态、气质和镜头表现几乎无短板，现实中基本不存在。"] },
  career: { label:"职业发展", short:"结合城市、稳定性、收入与成长性", descriptions:[
    "未评分。","1分｜无稳定工作或长期失业，收入中断且没有清晰职业计划。","2分｜临时工、频繁换岗或高度不稳定的小微企业岗位，收入明显低于当地水平。","3分｜普通小型民企或基础服务岗位，能够就业，但稳定性、收入和成长空间都有限。","4分｜稳定的中小企业、技术或行政岗位，收入接近当地普通水平，有一定可积累能力。","5分｜成熟民企正式员工、专业技术岗位，或三四线城市一般国企/事业单位岗位，稳定与收入较均衡。","6分｜优质国企正式岗、地方银行稳定岗、低线城市公务员/事业编，或中型科技企业骨干，抗风险能力较好。","7分｜新一线/二线城市公务员或优质事业编、银行核心正式岗、大型国企骨干，或IT大厂成熟专业岗。","8分｜一线城市优质公务员/事业单位核心岗、央国企或银行总部骨干；IT大厂高级岗可达此级，但需扣除裁员风险。","9分｜一线城市核心体制内/央国企重要岗位，兼具稀缺平台、明确晋升与优厚保障；头部银行核心高薪岗也可接近。","10分｜一线城市极稀缺的核心体制内或中央级平台：稳定、待遇、资源、发展和社会认可几乎同时拉满，现实中极少。"] },
  family: { label:"家庭支持", short:"氛围、负担与边界", descriptions:[
    "原生家庭存在严重冲突或债务负担，且缺乏必要的个人边界。","家庭干预强、负担重，个人很难独立做出婚恋与生活决策。","有较明显的经济或照护压力，对亲密关系可能产生持续影响。","家庭支持有限但基本可控，边界问题仍需要双方耐心协商。","家庭关系和负担处于普通水平，重大事项可以进行基本沟通。","家庭氛围相对友善，经济与养老安排较清晰，尊重个人选择。","能提供稳定情感支持，家庭边界清晰，现实负担相对较轻。","双方父母开明、关系健康，能在需要时提供适度实际支持。","家庭资源、氛围和边界都很理想，对新家庭形成明显助力。","家庭高度和谐且保障充分，能够长期尊重并支持小家庭独立。","极其理想的支持系统：温暖、开明、低负担且资源充足。"] },
};

const targetInfo: Record<TargetKind,{name:string;tag:string;copy:string;color:string}> = {
  compatible:{name:"轻松相处型",tag:"更容易",copy:"条件门槛更包容，侧重稳定性与现实适配。",color:"mint"},
  balanced:{name:"势均力敌型",tag:"较均衡",copy:"综合条件接近，现实基础与关系质量兼顾。",color:"purple"},
  aspirational:{name:"理想进阶型",tag:"更有挑战",copy:"多项条件突出，候选更稀缺，匹配难度更高。",color:"yellow"},
};

function clamp(v:number,min=0,max=100){return Math.min(max,Math.max(min,v))}
function metricScore(key:keyof Profile,p:Profile){const v=p[key];if(typeof v!=="number")return 50;switch(key){case"age":{const ideal=p.gender==="男"?30:27;return clamp(100-Math.abs(p.age-ideal)*(p.age>ideal?4.2:2.4))}case"height":{const mean=p.gender==="男"?169.7:158,sd=p.gender==="男"?6.5:6,z=(p.height-mean)/sd;return clamp(100/(1+Math.exp(-1.702*z)),2,98)}case"appearance":return p.appearance*10;case"education":return [35,50,66,78,89,96][p.education]??50;case"income":{const baseline={"一线":18,"新一线":12,"二线":9,"三线及以下":7}[p.city]??10;return clamp(50+30*Math.log2(Math.max(.2,p.income/baseline)),5,98)}case"savings":{const baseline={"一线":30,"新一线":20,"二线":15,"三线及以下":10}[p.city]??15;return clamp(50+25*Math.log2(Math.max(.2,p.savings/baseline)),5,98)}case"career":case"family":return p[key]*10;default:return 50}}
function calculate(p:Profile,weights:WeightItem[]){const active=weights.filter(w=>w.enabled),total=active.reduce((s,w)=>s+w.weight,0)||1;const dimensions=active.map(w=>({...w,score:Math.round(metricScore(w.key,p))}));const score=Math.round(dimensions.reduce((s,w)=>s+w.score*w.weight,0)/total);const percentile=Math.round(clamp(50+(score-62)*2.15,3,98));const groups=modelGroups.map(group=>{const items=dimensions.filter(item=>group.keys.includes(item.key)),weight=items.reduce((s,item)=>s+item.weight,0),groupScore=weight?Math.round(items.reduce((s,item)=>s+item.score*item.weight,0)/weight):0;return{...group,weight:weight/total*100,score:groupScore}});return{score,percentile,dimensions,groups}}
function difficulty(own:number,target:number){const gap=target-own;if(gap<=-5)return{label:"容易",step:5,copy:"目标画像的综合门槛更宽松，条件层面较容易形成双向选择。"};if(gap<=1)return{label:"较易",step:4,copy:"双方综合条件接近，进入彼此选择范围的可能性相对较高。"};if(gap<=5)return{label:"适中",step:3,copy:"存在一定条件差，需要靠偏好契合与相处质量补足。"};if(gap<=9)return{label:"较难",step:2,copy:"目标相对稀缺，需要更强的个人特色或关系优势。"};return{label:"很难",step:1,copy:"目标画像非常稀缺，仅从条件层面看双向选择门槛较高。"}}

function InfoDot({text}:{text:string}){return <span className="info-dot" tabIndex={0} aria-label={text}>i<span>{text}</span></span>}
function itemInfo(key:keyof Profile|null,p:Profile,weights:WeightItem[]){if(!key)return"该项用于确定人群比较口径，不直接计入总分。";const active=weights.filter(w=>w.enabled),total=active.reduce((s,w)=>s+w.weight,0)||1,w=active.find(x=>x.key===key);if(!w)return"该项当前已在模型设置中停用，不计入总分。";const score=Math.round(metricScore(key,p)),normalized=w.weight/total*100,contribution=score*w.weight/total;const basis=key==="height"?` 身高以${p.gender==="男"?"169.7":"158.0"}cm平均值为50分基准。`:key==="income"?` 当前按${p.city}城市年收入基线校准。`:key==="savings"?` 当前按${p.city}城市存款基线校准。`:"";return`当前单项 ${score}/100 · 总分权重 ${normalized.toFixed(1)}% · 贡献 ${contribution.toFixed(1)} 分。${basis}`}

function NumberField({label,value,onChange,unit,min=0,max=999,info}:{label:string;value:number;onChange:(v:number)=>void;unit?:string;min?:number;max?:number;info?:string}){
  const[draft,setDraft]=useState(String(value));
  useEffect(()=>setDraft(String(value)),[value]);
  const change=(raw:string)=>{setDraft(raw);if(raw!==""){const parsed=Number(raw);if(Number.isFinite(parsed))onChange(parsed)}};
  const finish=()=>{if(draft===""){setDraft(String(value));return}const parsed=Number(draft);const next=Math.min(max,Math.max(min,Number.isFinite(parsed)?parsed:value));setDraft(String(next));if(next!==value)onChange(next)};
  return <label className="field"><span className="field-label">{label}{info&&<InfoDot text={info}/>}</span><div><input aria-label={label} type="number" inputMode="numeric" step="1" value={draft} min={min} max={max} onFocus={e=>e.currentTarget.select()} onChange={e=>change(e.target.value)} onBlur={finish}/>{unit&&<em>{unit}</em>}</div></label>
}

function SoftSlider({kind,value,onChange,city}:{kind:SoftKey;value:number;onChange:(v:number)=>void;city:string}){const meta=softMeta[kind];return <div className="soft-card"><div className="soft-title"><div><b>{meta.label}</b><span>{meta.short}</span></div><strong>{value}<small>/10</small></strong></div><input aria-label={`${meta.label}评分`} type="range" min="1" max="10" step="1" value={value} onChange={e=>onChange(Number(e.target.value))}/><div className="scale"><span>1</span><span>5</span><span>10</span></div><p key={value}><i>当前等级</i>{meta.descriptions[value]}</p>{kind==="appearance"&&<small className="model-caveat">仅描述大众审美中的相对位置，不代表个人价值。</small>}{kind==="career"&&<small className="model-caveat">当前选择：{city}城市口径。IT大厂等高薪岗位会同时考虑波动和裁员风险。</small>}</div>}

function Basics({profile,onChange,weights}:{profile:Profile;onChange:(p:Profile)=>void;weights:WeightItem[]}){const set=<K extends keyof Profile>(k:K,v:Profile[K])=>onChange({...profile,[k]:v});return <><div className="basics-grid"><label className="field"><span className="field-label">性别<InfoDot text={itemInfo(null,profile,weights)}/></span><select value={profile.gender} onChange={e=>set("gender",e.target.value as Profile["gender"])}><option>男</option><option>女</option></select></label><NumberField label="年龄" value={profile.age} min={18} max={65} unit="岁" info={itemInfo("age",profile,weights)} onChange={v=>set("age",v)}/><label className="field"><span className="field-label">常住城市<InfoDot text={itemInfo(null,profile,weights)}/></span><select value={profile.city} onChange={e=>set("city",e.target.value)}><option value="一线">一线（北上广深）</option><option value="新一线">新一线（15城）</option><option>二线</option><option>三线及以下</option></select></label><NumberField label="身高" value={profile.height} min={140} max={210} unit="cm" info={itemInfo("height",profile,weights)} onChange={v=>set("height",v)}/><label className="field"><span className="field-label">最高学历<InfoDot text={itemInfo("education",profile,weights)}/></span><select value={profile.education} onChange={e=>set("education",Number(e.target.value))}>{educationLabels.map((x,i)=><option value={i} key={x}>{x}</option>)}</select></label><NumberField label="税前年收入" value={profile.income} unit="万" info={itemInfo("income",profile,weights)} onChange={v=>set("income",v)}/><NumberField label="可支配储蓄" value={profile.savings} unit="万" info={itemInfo("savings",profile,weights)} onChange={v=>set("savings",v)}/></div>{profile.city==="新一线"&&<div className="city-explain"><b>新一线 · 2025榜单口径</b><span>{newFirstTierCities.join("、")}</span><small>这是第一财经的商业魅力榜单，并非行政级别。2026年报告已停止发布城市排名与分级。</small><a href="https://www.yicai.com/news/102638963.html" target="_blank" rel="noreferrer">查看来源</a></div>}</>}

function ResultHero({profile,weights}:{profile:Profile;weights:WeightItem[]}){const result=useMemo(()=>calculate(profile,weights),[profile,weights]);const[showParts,setShowParts]=useState(false);const top=[...result.dimensions].sort((a,b)=>b.score-a.score)[0],total=result.dimensions.reduce((s,x)=>s+x.weight,0)||1;return <section className="result-hero"><div className="result-copy"><span className="mini-label">你的条件画像</span><h1>{result.percentile>=82?"优势清晰型":result.percentile>=65?"稳健平衡型":"成长潜力型"}</h1><p>你的综合条件呈现出稳定、均衡的基础。<b>{top?.label}</b>是当前最鲜明的优势。</p><div className="result-actions"><button onClick={()=>document.querySelector("#profile-editor")?.scrollIntoView({behavior:"smooth"})}>调整我的资料</button><span>同口径：{profile.gender} · {profile.city} · 25–34 岁</span></div></div><div className="result-visual"><div className="orbit one"/><div className="orbit two"/><div className="avatar-shape"><i/><b/><span/></div></div><div className={`score-summary ${showParts?"parts-view":""}`}>{showParts?<><div className="score-mode-head"><small>分项得分</small><button onClick={()=>setShowParts(false)}>← 返回总分</button></div><div className="group-scores">{result.groups.map(group=><div key={group.key} style={{borderColor:group.color}}><span>{group.label}<small>{group.weight.toFixed(0)}%</small></span><strong>{group.score}</strong></div>)}</div><div className="score-parts">{result.dimensions.map(item=><div key={item.key}><span>{item.label}<small>权重 {(item.weight/total*100).toFixed(1)}%</small></span><i><b style={{width:`${item.score}%`}}/></i><strong>{item.score}</strong></div>)}</div><p className="formula-note">外观、经济、其他三级汇总后得到综合分。</p></>:<><div className="score-mode-head"><small>综合条件分</small><button onClick={()=>setShowParts(true)}>查看分项 →</button></div><strong>{result.score}</strong><span>/100</span><div className="percent-bar"><i style={{width:`${result.percentile}%`}}/></div><p>高于同口径人群的 <b>{result.percentile}%</b></p></>}</div></section>}

function ProfileEditor({profile,onChange,weights}:{profile:Profile;onChange:(p:Profile)=>void;weights:WeightItem[]}){const set=(k:SoftKey,v:number)=>onChange({...profile,[k]:v});return <section className="editor-section" id="profile-editor"><div className="section-heading"><span>01</span><div><h2>完善你的条件画像</h2><p>拖动评分时，对应等级的具体行为描述会同步变化。</p></div></div><div className="white-panel"><h3>基础条件</h3><Basics profile={profile} onChange={onChange} weights={weights}/></div><div className="soft-grid">{(Object.keys(softMeta) as SoftKey[]).map(k=><SoftSlider key={k} kind={k} value={profile[k]} city={profile.city} onChange={v=>set(k,v)}/>)}</div></section>}

function TargetEditor({target,onChange,ownScore,weights}:{target:Profile;onChange:(p:Profile)=>void;ownScore:number;weights:WeightItem[]}){const result=calculate(target,weights),level=difficulty(ownScore,result.score);const set=(k:SoftKey,v:number)=>onChange({...target,[k]:v});return <div className="target-editor"><div className="target-live"><div><span>当前目标分</span><strong>{result.score}</strong><small>/100</small></div><div className="difficulty"><span>匹配难度</span><b>{level.label}</b><div>{[1,2,3,4,5].map(n=><i className={n<=level.step?"on":""} key={n}/>)}</div></div><p>{level.copy}</p></div><div className="white-panel"><h3>调整目标基础条件</h3><Basics profile={target} onChange={onChange} weights={weights}/></div><div className="target-soft">{(Object.keys(softMeta) as SoftKey[]).map(k=><SoftSlider key={k} kind={k} value={target[k]} city={target.city} onChange={v=>set(k,v)}/>)}</div></div>}

function SettingsPage({weights,setWeights,saved,onSave}:{weights:WeightItem[];setWeights:(next:WeightItem[])=>void;saved:boolean;onSave:()=>void}){const active=weights.filter(w=>w.enabled),total=active.reduce((s,w)=>s+w.weight,0)||1;return <section className="settings-page"><div className="page-intro"><span className="mini-label">模型设置 · V0.3</span><h1>先看外观，再看经济</h1><p>新模型按真实初筛顺序组织：外观条件40%、经济条件38%、其他条件22%。后台调整后会自动重新归一化。</p></div><div className="group-rule-cards">{modelGroups.map(group=>{const weight=active.filter(w=>group.keys.includes(w.key)).reduce((s,w)=>s+w.weight,0)/total*100;return <div key={group.key} style={{borderTopColor:group.color}}><span>{group.label}</span><strong>{weight.toFixed(0)}%</strong><small>{group.keys.map(key=>weights.find(w=>w.key===key)?.label).filter(Boolean).join(" · ")}</small></div>})}</div><div className="settings-card"><div className="settings-head"><div><h2>子项权重</h2><p>启用权重合计 {active.reduce((s,w)=>s+w.weight,0)}，计算时自动归一化</p></div><button onClick={onSave}>{saved?"已保存 ✓":"保存设置"}</button></div>{weights.map((w,i)=><div className={`weight-line ${!w.enabled?"off":""}`} key={w.key}><span>{w.label}</span><input type="range" min="1" max="30" value={w.weight} onChange={e=>setWeights(weights.map((x,n)=>n===i?{...x,weight:Number(e.target.value)}:x))}/><strong>{w.weight}%</strong><button aria-label={`${w.enabled?"停用":"启用"}${w.label}`} className={w.enabled?"toggle on":"toggle"} onClick={()=>setWeights(weights.map((x,n)=>n===i?{...x,enabled:!x.enabled}:x))}><i/></button></div>)}</div><div className="research-card"><div><span>为什么这样调整</span><h2>行为证据比口头偏好更可靠</h2></div><ul><li><b>外观40%</b><p>在线约会的第一轮筛选速度很快，外貌是最强预测项；身高按同性别人口平均值转为相对位置，再并入外观条件。</p></li><li><b>经济38%</b><p>中国婚恋平台行为数据表明，女性对男性收入与教育更敏感。收入、存款按城市生活成本分档，家庭支持作为长期资源的一部分。</p></li><li><b>其他22%</b><p>年龄在实际联络中具有明显筛选作用；职业用于修正收入稳定性；教育保留但降为最低权重，避免和收入、职业重复计分。</p></li></ul><div className="source-links"><a href="https://doi.org/10.1016/j.chbr.2024.100579" target="_blank" rel="noreferrer">2024在线约会联合分析</a><a href="https://arxiv.org/abs/1401.5710" target="_blank" rel="noreferrer">中国婚恋网站行为研究</a><a href="https://www.nhc.gov.cn/xcs/c100122/202012/175301a949ce481a9c1a9a2b393c8e49.shtml" target="_blank" rel="noreferrer">卫健委身高基线</a><a href="https://www.stats.gov.cn/xxgk/sjfb/zxfb2020/202601/t20260119_1962321.html" target="_blank" rel="noreferrer">国家统计局收入数据</a></div><p className="assumption-note">数据边界：官方资料提供身高均值和居民收入总体水平，但没有覆盖城市×年龄×婚姻状态的完整微观分布；城市收入与存款基线仍是可在后台替换的工程估计，不应理解为精确人口统计结论。</p></div></section>}

export default function Home(){const[page,setPage]=useState<"profile"|"match"|"settings">("profile");const[profile,setProfile]=useState(profileSeed);const[targets,setTargets]=useState(targetSeeds);const[active,setActive]=useState<TargetKind>("balanced");const[weights,setWeights]=useState(weightsSeed);const[saved,setSaved]=useState(false);useEffect(()=>{const raw=localStorage.getItem("hepan-config-v3");if(raw)try{const old=JSON.parse(raw) as WeightItem[];setWeights(weightsSeed.map(seed=>{const stored=old.find(item=>item.key===seed.key);return stored?{...seed,weight:stored.weight,enabled:stored.enabled}:seed}))}catch{}},[]);const own=calculate(profile,weights);const updateTarget=(p:Profile)=>setTargets({...targets,[active]:p});const save=()=>{localStorage.setItem("hepan-config-v3",JSON.stringify(weights));setSaved(true);setTimeout(()=>setSaved(false),1600)};
  return <main><header><button className="logo" onClick={()=>setPage("profile")}><i>H</i><span>Hepan<small>条件匹配实验室</small></span></button><nav><button className={page==="profile"?"active":""} onClick={()=>setPage("profile")}>我的画像</button><button className={page==="match"?"active":""} onClick={()=>setPage("match")}>目标推荐</button><button className={page==="settings"?"active":""} onClick={()=>setPage("settings")}>模型设置</button></nav><div className="privacy"><i/>资料仅保存在本机</div></header>
  {page==="profile"&&<><ResultHero profile={profile} weights={weights}/><ProfileEditor profile={profile} onChange={setProfile} weights={weights}/></>}
  {page==="match"&&<section className="match-page"><div className="page-intro"><span className="mini-label">基于你的 {own.score} 分生成</span><h1>三个值得考虑的目标画像</h1><p>选择一种方向，再自由移动对方的各项指标。总分和匹配难度会实时变化。</p></div><div className="target-cards">{(Object.keys(targetInfo) as TargetKind[]).map(k=>{const r=calculate(targets[k],weights),info=targetInfo[k],d=difficulty(own.score,r.score);return <button key={k} className={`${info.color} ${active===k?"selected":""}`} onClick={()=>setActive(k)}><span>{info.tag}</span><div className="target-icon"><i/><b/></div><h2>{info.name}</h2><p>{info.copy}</p><div className="target-score"><strong>{r.score}</strong><small>分</small><em>{d.label}</em></div></button>})}</div><TargetEditor target={targets[active]} onChange={updateTarget} ownScore={own.score} weights={weights}/></section>}
  {page==="settings"&&<SettingsPage weights={weights} setWeights={setWeights} saved={saved} onSave={save}/>} {/* settings view */}
  <footer><b>Hepan</b><span>结果用于自我认知和偏好梳理，不代表人的价值。</span><a href="https://www.16personalities.com/free-personality-test" target="_blank" rel="noreferrer">界面风格参考</a></footer></main>}
